server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://mysql-184406-0.cloudclusters.net:10137/jwt
    username: admin
    password: 7Q5TojCl
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect